# Generated by Django 4.0.3 on 2022-04-20 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_profile_last_sent_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_sent_email',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 20, 18, 44, 50, 106561)),
        ),
    ]
