# Generated by Django 4.0.3 on 2022-05-03 13:35

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_profile_friends_alter_profile_last_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pending_friend_requests',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_sent_email',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 16, 35, 0, 293794)),
        ),
    ]
