# Generated by Django 4.0.3 on 2022-05-03 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_profile_pending_friend_requests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/default_image_qvmqoi.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_sent_email',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 18, 57, 59, 81445)),
        ),
    ]
