# Generated by Django 4.0.3 on 2022-05-09 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_profile_parent_email_profile_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_sent_email',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 17, 24, 40, 986916)),
        ),
    ]
