# Generated by Django 4.0.3 on 2022-05-09 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_resetpassworddata_alter_profile_last_sent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassworddata',
            name='token_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_sent_email',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 9, 19, 37, 58, 842296)),
        ),
    ]
