# Generated by Django 4.0.3 on 2022-05-24 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_resetpassworddata_token_submit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_sent_email',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 18, 41, 7, 568441)),
        ),
    ]
