# Generated by Django 4.0.3 on 2022-04-02 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('da_day', '0002_questions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
