# Generated by Django 4.0.3 on 2022-04-02 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_day', '0003_rename_questions_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 2, 21, 8, 54, 33966)),
        ),
    ]
