<<<<<<< Updated upstream
# Generated by Django 4.0.3 on 2022-04-03 13:04
=======
# Generated by Django 4.0.3 on 2022-04-04 15:08
>>>>>>> Stashed changes

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_day', '0009_alter_note_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
<<<<<<< Updated upstream
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 13, 4, 26, 123294)),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 18, 8, 47, 201806)),
>>>>>>> Stashed changes
        ),
    ]
